services:
  - type: web
    name: myportfolio
    env: python
    buildCommand: ""
    startCommand: gunicorn portfolio.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
      - key: PYTHON_VERSION
        value: 3.10
